server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://172.17.0.2:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "3HokT6+YLtwnAAnfgu0gDoqo0Z+bIl3qj6nO4MxdzjECDxi7FMXYlNZYSwdXSAFK"
  valid-duration: 3600
  refreshable-duration: 36000
